project:
  type: website
  output-dir: docs
  
website:
  title: "Sarah Zhang"
  navbar:
    left:
      - about.qmd
      - href: CV.pdf
        text: Resume

format:
  html:
    theme: lux
    css: styles.css
    toc: true
